version: '3.7'
services:
  postgres:
    image: postgres:10.5
    restart: always
    env_file:
    - .env
    volumes:
    - postgres:/var/lib/postgresql/data
    networks:
    - blog-network
  prisma:
    image: prismagraphql/prisma:1.18
    restart: always
    ports:
    - "${PRISMA_PORT}:4466"
    networks:
    - blog-network
    depends_on:
    - postgres
    environment:
      PRISMA_CONFIG_PATH: /app/prisma/prisma_config.yml
    volumes:
    - ./prisma/:/app/prisma/
volumes:
  postgres:
networks:
  blog-network:
    name: blog-network-${COMPOSE_PROJECT_NAME}
    driver: bridge
