version: '3.7'
services:
  postgres:
    image: postgres:10.5
    restart: always
    env_file:
    - ../config/internal.env
    - ../config/secret.env
    environment:
      PGDATA: /var/lib/postgresql/data
    networks:
    - blog-network
    tmpfs:
    - /var/lib/postgresql/data:rw
  prisma:
    image: prismagraphql/prisma:1.18
    restart: always
    ports:
    - "${PRISMA_PORT}:4466"
    networks:
    - blog-network
    depends_on:
    - postgres
    environment:
      PRISMA_CONFIG_PATH: /app/prisma/prisma_config.yml
    volumes:
    - ../prisma/:/app/prisma/
networks:
  blog-network:
    name: blog-network-${COMPOSE_PROJECT_NAME}
    driver: bridge
