version: '3.7'
services:
  bash:
    image: blog-image:dev
    volumes:
    - ../server/src:/home/workdir/src
    env_file:
    - ../config/internal.env
    - ../config/secret.env
    networks:
    - blog-network
    entrypoint:
    - bash
networks:
  blog-network:
    name: blog-network-${COMPOSE_PROJECT_NAME}
    driver: bridge
