version: '3.7'
services:
  e2e:
    image: blog-image:dev
    entrypoint: |
      bash -c "dockerize -wait http://prisma:4466 -timeout 60s yarn gulp deploy &&
        yarn nodemon -e ts,graphql -x ts-node e2e/server.ts"
    restart: on-failure
    networks:
    - blog-network
    volumes:
    - ../server/src:/home/workdir/src/
    - ../server/e2e:/home/workdir/e2e/
    env_file:
    - ../config/internal.env
    - ../config/secret.env
