version: '3.7'
services:
  test:
    image: blog-image:dev
    entrypoint:
    - dockerize
    - -wait
    - http://prisma:4466
    - -timeout
    - 60s
    - yarn
    - gulp
    - test
    restart: on-failure
    networks:
    - blog-network
    volumes:
    - ../server/src:/home/workdir/src/
    - ../server/test:/home/workdir/test/
    env_file:
    - ../config/internal.env
    - ../config/secret.env