projects:
  prisma:
    schemaPath: src/generated/prisma.graphql
    includes: [
      "prisma.graphql",
      "datamodel.graphql",
    ]
    extensions:
      prisma: prisma/prisma.yml
      codegen:
      - generator: prisma-binding
        language: typescript
        output:
          binding: src/generated/prisma.ts
