version: '3.7'
services:
  postgres:
    image: postgres:10.5
    restart: always
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    volumes:
    - postgres:/var/lib/postgresql/data
    networks:
    - blog-network
  prisma:
    image: prismagraphql/prisma:1.18
    restart: always
    ports:
    - "4466:4466"
    networks:
    - blog-network
    depends_on:
    - postgres
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: postgres
            host: postgres
            port: 5432
            user: prisma
            password: prisma
            migrations: true
  seed-prisma:
    build: .
    entrypoint:
      - yarn
      - deploy
    restart: on-failure
    networks:
    - blog-network
    volumes:
    - ./src/generated:/home/workdir/src/generated
    depends_on:
    - prisma
    env_file:
    - .env
  server:
    build: .
    ports:
    - "4000:4000"
    entrypoint:
      - yarn
      - start
    restart: always
    networks:
    - blog-network
    depends_on:
    - prisma
    volumes:
    - ./src:/home/workdir/src/
    env_file:
    - .env
volumes:
  postgres:
networks:
  blog-network:
    name: blog-network
    driver: bridge
