version: '3.7'
services:
  postgres:
    image: postgres:10.5
    container_name: postgres-${ENV}
    restart: always
    env_file:
    - .env
    volumes:
    - postgres:/var/lib/postgresql/data
    networks:
    - blog-network
  prisma:
    image: prismagraphql/prisma:1.18
    container_name: prisma-${ENV}
    restart: always
    ports:
    - "4466:4466"
    networks:
    - blog-network
    depends_on:
    - postgres
    environment:
      PRISMA_CONFIG_PATH: /home/build/prisma_config.yml
    volumes:
    - ./build/:/home/build/
  build-prisma:
    build: .
    container_name: build-prisma-${ENV}
    entrypoint:
    - yarn
    - deploy
    restart: on-failure
    networks:
    - blog-network
    volumes:
    - ./src/generated:/home/workdir/src/generated
    depends_on:
    - prisma
    env_file:
    - .env
  server:
    build: .
    container_name: server-${ENV}
    ports:
    - "4000:4000"
    entrypoint:
    - yarn
    - start
    restart: always
    networks:
    - blog-network
    depends_on:
    - prisma
    volumes:
    - ./src:/home/workdir/src/
    env_file:
    - .env
volumes:
  postgres:
networks:
  blog-network:
    name: blog-network-${ENV}
    driver: bridge
