version: '3.7'
services:
  bash:
    build: .
    entrypoint:
    - /bin/sh
    restart: on-failure
    networks:
    - blog-network
    depends_on:
    - build-prisma
    volumes:
    - ./src:/home/workdir/src/
    - ./test:/home/workdir/test/
    env_file:
    - .env
networks:
  blog-network:
    name: ${NETWORK_NAME}
    driver: bridge
