version: '3.5'
services:
  prisma:
    image: prismagraphql/prisma:1.17
    restart: always
    ports:
    - "4466:4466"
    networks:
    - blog-network
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: postgres
            host: postgres
            port: 5432
            user: prisma
            password: prisma
            migrations: true
  postgres:
    image: postgres:10.5
    restart: always
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    volumes:
    - postgres:/var/lib/postgresql/data
    networks:
    - blog-network
  seed-prisma:
    build: .
    entrypoint:
      - yarn
      - deploy
    restart: on-failure
    networks:
    - blog-network
  server:
    build: .
    ports:
    - "4000:4000"
    entrypoint:
      - yarn
      - start
    networks:
    - blog-network
    volumes:
    - .:/home/workdir/
volumes:
  postgres:
networks:
  blog-network:
    name: blog-network
    driver: bridge
