version: '3.7'
services:
  test:
    build: .
    container_name: test-${ENV}
    entrypoint:
      - yarn
      - ts-node
      - test/server.ts
    restart: on-failure
    networks:
    - blog-network
    depends_on:
    - prisma
    volumes:
    - ./src:/home/workdir/src/
    - ./test:/home/workdir/test/
    env_file:
    - .env
networks:
  blog-network:
    name: blog-network-${ENV}
    driver: bridge
