version: '3.7'
services:
  bash:
    image: blog-image:dev
    restart: on-failure
    volumes:
    - ./server/src:/home/workdir/src
    env_file:
    - .env
    networks:
    - blog-network
networks:
  blog-network:
    name: blog-network-${COMPOSE_PROJECT_NAME}
    driver: bridge
