version: '3.7'
services:
  postgres:
    image: postgres:10.5
    restart: always
    env_file:
    - .env
    volumes:
    - postgres:/var/lib/postgresql/data
    networks:
    - blog-network
  prisma:
    image: prismagraphql/prisma:1.18
    restart: always
    ports:
    - "${PRISMA_PORT}:4466"
    networks:
    - blog-network
    depends_on:
    - postgres
    environment:
      PRISMA_CONFIG_PATH: /home/config/prisma_config.yml
    volumes:
    - ./config/:/home/config/
  build-prisma:
    image: blog-image:dev
    entrypoint:
    - dockerize
    - -wait
    - http://prisma:4466
    - yarn
    - deploy
    restart: on-failure
    networks:
    - blog-network
    volumes:
    - ./src/generated:/home/workdir/src/generated
    depends_on:
    - prisma
    env_file:
    - .env
  server:
    image: blog-image:dev
    ports:
    - "${SERVER_PORT}:4000"
    entrypoint:
    - yarn
    - start
    restart: always
    networks:
    - blog-network
    depends_on:
    - prisma
    volumes:
    - ./src:/home/workdir/src/
    env_file:
    - .env
volumes:
  postgres:
networks:
  blog-network:
    name: blog-network-${COMPOSE_PROJECT_NAME}
    driver: bridge
