version: '3.7'
services:
  build-dev:
    image: blog-image:dev
    entrypoint:
    - dockerize
    - -wait
    - http://prisma:4466
    - yarn
    - gulp
    - build-dev
    restart: on-failure
    networks:
    - blog-network
    volumes:
    - ./server/src:/home/workdir/src
    env_file:
    - .env
