version: '3.7'
services:
  bash:
    image: blog-image:dev
    entrypoint:
    - /bin/sh
    restart: on-failure
    networks:
    - blog-network
    depends_on:
    - build-prisma
    volumes:
    - ./src:/home/workdir/src/
    - ./test:/home/workdir/test/
    env_file:
    - .env
