version: '3.7'
services:
  seed:
    build: .
    container_name: seed-${ENV}
    entrypoint:
    - yarn
    - ts-node
    - src/seed.ts
    - src/seed.graphql
    restart: on-failure
    networks:
    - blog-network
    volumes:
    - ./src:/home/workdir/src/
    env_file:
    - .env
networks:
  blog-network:
    name: blog-network-${ENV}
    driver: bridge
