version: '3.7'
services:
  test:
    image: blog-image:dev
    entrypoint:
    - dockerize
    - -wait
    - http://prisma:4466
    - yarn
    - ts-node
    - test/server.ts
    restart: on-failure
    networks:
    - blog-network
    depends_on:
    - prisma
    volumes:
    - ./src:/home/workdir/src/
    - ./test:/home/workdir/test/
    env_file:
    - .env
