version: '3.7'
services:
  test:
    image: blog-image:dev
    entrypoint:
    - dockerize
    - -wait
    - http://prisma:4466
    - yarn
    - gulp
    - test
    networks:
    - blog-network
    volumes:
    - ./server/src:/home/workdir/src/
    - ./server/test:/home/workdir/test/
    env_file:
    - .env
