version: '3.7'
services:
  seed:
    image: blog-image:dev
    entrypoint:
    - dockerize
    - -wait
    - http://prisma:4466
    - yarn
    - ts-node
    - src/seed.ts
    - src/seed.graphql
    restart: on-failure
    networks:
    - blog-network
    volumes:
    - ./src:/home/workdir/src/
    env_file:
    - .env
